### ISSUE TITLE
Nr. 1 ListPage with Ads

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#1]
## Value proposition

As an user
I need to see a list of all given ads with a short overview of the important data like name, title, picture and costs.
to be able to find out which is the best Ad for me.

## Description

![ListPageWirefram](https://user-images.githubusercontent.com/112754397/201702055-ef6a2c74-a910-4b31-beb5-2800fb734615.png)

## Acceptance criteria
- the ListPage must be there
- the ListPage should show all Ads
- the Ads should be sorted by Date
- the Headline should show how many Ads has been found

## Tasks

- [x] create Featurebranch "ListPage"
- [x] create ListPage with Headline "I found X Heroes for you:"
- [x] create Counter for Ads inside X
- [x] create an Array with Ad Dummydata (id, Name, TaskOffertitle, TaskDescription, TaskPicture,createdDate, Profilpicture)
- [x] Create Ads Componnent with Picture, Title, Date, Profilpicture and UserName
- [x] fetch DummyData
- [x] map DummyData inside Ad Component

## Complexity Estimation

M
