### ISSUE TITLE
Nr. 9 User Login

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#14]
## Value proposition

As an user
I need to login in the app,
so that I can see my profil information and only can change my ads.

## Description

![Image](https://user-images.githubusercontent.com/112754397/203843676-aa31da05-5eb5-4e3f-8e54-bd72510516d1.png)
![Image](https://user-images.githubusercontent.com/112754397/203843675-f0c71069-3593-4623-a661-95a310b1dd12.png)
![Image](https://user-images.githubusercontent.com/112754397/203843677-b62f2bcc-e58e-4002-b396-90f89649555b.png)

## Acceptance criteria

- the profilinformation like username, userpicture, karma account should be shown on every site
- the profilinformation includes username, userpicture, karma account, email and telephone
- login must be possible via username and password
- after succesfully log in there should be a redirection to the searchpage
- it should be able to logout
- after clicking the logout a redirect to the loginpage should happen
- the user can only edit and delete his own ads
- only the logged in user should be able to create new ads
- username, userpicture email and telephone should be append as default to new ads
- if the login fails a message should appear
- users which are not logged in should be able to see ads

## Tasks

- [x] create feature branch
- [x] build login page with username and password (password will be not checked)
- [x] logged in users are saved in localstorage
- [x] create logout button with redirect to loginpage and delete from localstorage
- [x] build header with profildetails like Username, karma account and logout
- [x] build protected component with page as {Children}
- [x] create user collection of 3-4 users (userId, Name, Password, karma account, userPictureSrc, telephone & email)
- [x] fetch user collection
- [x] login checks which user is logged in then renders the header 
- [x] only render edit and delete wenn logged in user is equal to Aduser
- [x] refactor AddAd component
- [x] refactor Ad fetches and rendering

## Complexity Estimation

XL
