### ISSUE TITLE
Nr. 10 karma account

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#15]
## Value proposition

As a user
I need to reward other users after booking they´re ad,
to be able to give and get Karma for ads.

## Description

![Image](https://user-images.githubusercontent.com/112754397/203843828-d6f8db4e-d20c-4d02-84d6-0c3bfcffe92f.png)

## Acceptance criteria

- the karma points should be always present
- after clicking book now the karma account should directly subtract  the amount of the ad costs
- the new karma points should directly append to the to the karma account of the ad-offering user
- a new user should have a default amount of karma points on his account

## Tasks

- [x] create feature branch "karmaAccount"
- [x] append costs to the book now button
- [ ] code a function which subtract the costs from karma account from the logged in user and update the displayed amount
- [ ] code a function which add the karma points to karma account from the ad offering user

## Complexity Estimation

M
