### ISSUE TITLE
Nr. 2 DetailsPage for each Ad

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#2]
## Value proposition

As an user
I need to see details of each Ad,
to be able to see which Ad fixes my problem the best.

## Description

![Image](https://user-images.githubusercontent.com/112754397/201955271-0eb7a732-7c02-4b98-a0e0-7f3ece8852b8.png)

![Image](https://user-images.githubusercontent.com/112754397/202405060-0f4f54c7-5af2-490f-a1f2-e31a0f23aa14.png)

## Acceptance criteria
- by clicking on an Ad at ListPage the Details should open 
- Details should include The Name of the Hero
- a describe picture,
- the TaskTitle
- a short addescription,
- the costs of the task,
- the category
- the tags for this Ad
- a go Back-to-List-Button ,
- by clicking on the Go-Back Button the User should lead back to the ListPage

## Tasks

- [x] create FeatureBranch "AdDetailsPage"
- [x] create an dynamic Detailspage
- [x] get ProfilPicture, UserName as an Prop
- [x] map Dummmydata (Headline, Desription)
- [x] build Go-Back-Button by using UseRouter
- [x] fetch Describe Picture from Unsplash

## Complexity Estimation

S

**Comment by ahohnsen** [comment]
Hey Julian,

Some thoughts I have:

- How can the user reach the details page? Please mention it in the acceptance criteria and it would be good to also show that in the wireframe. I would suggest to add a second wireframe to show where the user needs to click to reach the details page. 
- What happens if the user clicks the "go-back" button? You should be a bit more specific about that in your acceptance criteria e.g.: By clicking on the go-back button the user gets redirected to the ad list.
- In your wireframe it looks like your details page will have the headline "DetailsPage". 🤔 Do you really want that? Maybe you can think of something nicer here.
- Next to the hero's name there is a circle with a cross. I am not quite sure, what this is supposed to be. Please draw it in a different way or describe it in your acceptance criteria to make it more clear. 

Reminder: Please keep in mind that you want to describe all possible user interactions in your acceptance criteria.

**Comment by JulianHrt** [comment]
Hi @ahohnsen, Thank you for your Help. I made some edits and I made it clear now. :-)
