### ISSUE TITLE
Nr. 11 Accessibility

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#20]
## Value proposition

As a user
I need to understand what the icons mean
to be able to know whats happening if i click on it.

## Description

Every icon in the navbar have a short descriptive textlabel. 

## Acceptance criteria

- icons should be descriptive
- text should be descriptive
- all buttons  / clickable icons are  easily accessible

## Tasks

- [x] add text to icons
- [x] add icon to text
- [x] test acessiblity by using smartphone
- [x] add x to close login modal 

## Complexity Estimation
M
