### ISSUE TITLE
Nr. 12 image upload

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#21]
## Value proposition

As a user
I need to upload a picture for my ad
to be able to show other user what im offering.

## Description

![Image](https://user-images.githubusercontent.com/112754397/204847457-bd339f53-bc5c-4512-abf2-149f6eb63f0d.png)

## Acceptance criteria

- upload should be able by creating a new add
- title picture should be required 

## Tasks

- [x] create image cloud on cloudinary
- [x] create upload for images
- [x] delete code for random pictures from unsplash
- [x] delete settings from next.config
- [x] replace all images with images from cloudinary (including profile pictures)

## Complexity Estimation
S
