### ISSUE TITLE
Nr. 13 app design

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#22]
## Value proposition

As a User
I want to have a nice looking app
so that I have fun by using it.
​

## Description

The current design of find a hero with some more animations and colors.
The colors are specific for heros and included in the animations.
The create form should be good looking and take an example from material design.

## Acceptance criteria

- the design includes animations
- the design is minimalistic
- take care of mobile first and accessibility

## Tasks

- [x] build in more animations
- [x] set root colors and reuse them
- [x] style the input form 

## Complexity Estimation

M
