### ISSUE TITLE
Nr. 14 filter logged in users ads

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#23]
## Value proposition

As a User
I want to have a category for my own ads
so that I can find them fast. 
​

## Description

![Image](https://user-images.githubusercontent.com/112754397/204845844-f1845791-aa21-4e79-85d2-c8fb53b80d2d.png)

## Acceptance criteria

- the category should shown own the startpage with the other categories
- only logged in user can see the filter button 
- only logged in user can filter to there own ads

## Tasks

- [ ] build new filter button 
- [ ] build filter function with filtering by userId
- [ ] only render when logged in 
- [ ] setlastsearched back to "all" after logout 

## Complexity Estimation

S
