### ISSUE TITLE
Nr. 4 FormPage for Ads

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#4]
## Value proposition

As an user
I need to add my own Ads,
to be able to be Hero for others.

## Description

![Image](https://user-images.githubusercontent.com/112754397/201907531-8d03e61f-d0ba-4825-ab1b-0d74dc7e543a.png)

![Image](https://user-images.githubusercontent.com/112754397/202406585-7e22b7e7-e021-4c57-8265-5a08a8fe0515.png)

## Acceptance criteria

- it should be possible to add an Ad with
   Picture, Title, Description, Costs
- a categorie has to be selectable
- Email or Telefon is required
- title, category, tag and costs is required
-  if the required inputs are empty an Warning appears

## Tasks

- [x] create featurebranch called "FormPage"
- [x] build form component with Labels,Inputs,Checkboxes and Dropdown,Headline and Submitbutton
- [x] add the FormPage
- [x] code an Eventhandler for the Submitevent
- [x] code a Function whichs add the new Ad to the DummyDatasArray
- [x] append an Id to the Array generated by Using NanoID

## Complexity Estimation

L

**Comment by FelineHuhn** [comment]
From your story, I don't see how you come up with the form. Via a navigation or a button? Maybe you could show it in a wireframe too. Also you could show the form submit button in the wireframe. Otherwise it looks great to me. 

Just a little suggestion, maybe you could marker the required inputs with * in the wireframe, but it's just a matter of taste. 😃

**Comment by FelineHuhn** [comment]
Looks perfect to me :)

**Comment by ahohnsen** [comment]
As @FelineHuhn already mentioned you should display to the user which input fields are required, for example with *. 🙂 Otherwise it could be really frustrating for the user to fill out your form.

**Comment by JulianHrt** [comment]
thanks to @ahohnsen  and @FelineHuhn - I added your Idea with the * to my wireframe.
