### ISSUE TITLE
Nr. 5 EditPage for each Ad

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#5]
## Value proposition

As a user
I need to edit my Ads,
to be able to make Changes on my existing Ads.

## Description

![Image](https://user-images.githubusercontent.com/112754397/202407286-0bc517e5-021e-476f-898e-4f512f16dd2b.png)

![Image](https://user-images.githubusercontent.com/112754397/202406717-eec13b50-1371-4a87-9bb2-94f7e1a4a280.png)

## Acceptance criteria

- by clicking on the pen icon the user should lead to Editpage
- by clicking on the save-button the user should lead back to the Detailspage
- my Inputs are rewriteable
- i can edit the Ad on the AdDetailsPage
- i can save my editted Ad

## Tasks

- [x] create a featureBranch called like "editAd"
- [x] add an EditIcon
- [x] create an dynamic Editpage
- [x] take the Id as path
- [x] reuse the Addpage Component
- [x] set defaultValues via using Props

## Complexity Estimation

M

**Comment by ahohnsen** [comment]
Hey Julian,

I think you can be a bit more specific in your acceptance criteria, especially the user interactions. How does the user get to the EditPage? What happens when the user saves the changes?
As well, I am wondering if you have implemented the "Book now" button already in a previous user story? If not, you should remove it from your wireframe. This should be a separate feature. 🙂

**Comment by JulianHrt** [comment]
Hi @ahohnsen ,

i have add your Ideas to the  acceptance criteria. Thanks for that. The Book now button already exist in the previous user story. It leads to the contactPage :-)
