### ISSUE TITLE
Nr. 6 Delete Ad

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#6]
## Value proposition

As an user
I need to delete my Ads,
to be able to take back my offer.

## Description

![Image](https://user-images.githubusercontent.com/112754397/202407371-b90655a3-f531-46e7-acc5-bac9fbdf3706.png)

![Image](https://user-images.githubusercontent.com/112754397/202395764-820bf4c6-3fb6-4376-8c0e-c6264be11ff5.png)

## Acceptance criteria

- every Ad can be deleted
- the user can deleted the by clicking on the trash icon 
- before the deleting an Ad a warning appears and must be confirm
- after deleting an Ad the user should automatically return to the Listpage

## Tasks

- [x] create featureBranch "deleteAd"
- [x] add an deleteIcon
- [x] on click a new a Message "Are you sure?" with ConfirmButton should appear
- [x] on click on Confirm the Ad should be delete
- [x] UseRouter to push back to the ListPage
- [x] code a function which deletes the by using the id

## Complexity Estimation

L

**Comment by FelineHuhn** [comment]
Hey Julian, everything seems understandable to me and the wireframe is very nice and clear. Just a few little typos, but doesn't matter. And you maybe could show the delete modal message also in a wireframe? But that's up to you.

**Comment by JulianHrt** [comment]
Hi @FelineHuhn , thanks for your lovely feedback. I added an Wireframe for the modal.
