### ISSUE TITLE
Nr. 7 Navigation

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#7]
## Value proposition

As an user
I want to navigate through the app,
so that I can choose which page i see.

## Description

![Image](https://user-images.githubusercontent.com/112754397/203761819-c6f5e3f3-9c54-4541-a1b7-bb38b644503a.png)

## Acceptance criteria

- the ListPage, AddPage should be reachable
- the Navbar is at the Bottom of the App
- Links are icons
- active site is highlighted
- the navbar should be shown on every page 

## Tasks

- [x] create a Navbar component
- [x] Link to AddPage and Homepage
- [x] useRouter to higlight the icon

## Complexity Estimation

S
