### ISSUE TITLE
Nr. 8 Search by Category

### ISSUE THREAD

**Issue by JulianHrt** [JulianHrt/capstone-project-Find-a-Hero#8]
## Value proposition

As an user
I want to see the Ads of a specific type,
so that I can find the right one fast.

## Description

![Image](https://user-images.githubusercontent.com/112754397/203843354-ee15056d-7fee-41af-9ace-9bf20db0f605.png)

## Acceptance criteria

- the Categories should show as Buttons on the startpage 
- clicking a Category should lead to the list of Ads with this category
- if the user clicks on the search icon he is redirected to the startpage and can choose another category

## Tasks

- [x] create a new FeatureBranch "SearchByCategory"
- [x] create more Categories 
- [x] filter the Array before the rendering by selected Category
- [x] change categories into an array so adding a new Category by the admin create a new button and a new option in the form selection 
- [x] rename home to something more specific 

## Complexity Estimation
 M

**Comment by ahohnsen** [comment]
Hey Julian,

I have a few thoughts regarding your user story:
- I am wondering, what will be displayed when the user chooses the category "home"?
- What happens, when the user clicks on "home page" in the navigation? Will the same be displayed as when the user clicks on the "home" category? Does that mean that all ads will be displayed?
- I would suggest renaming "landing page" and "home page" in your navigation as the user might not know, what he/she can expect to see there.
- Probably it would be good to also rename the category "home" to avoid confusion 🤔 

> - the button should be dynamic so adding a new Categories ads a new button

Can the user add a new category and if yes, where/how can he/she do that?
